AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Chargeback API Lambda Function

Globals:
  Function:
    Timeout: 30
    MemorySize: 512
    Runtime: provided.al2
    Architectures:
      - x86_64

Resources:
  ChargebackApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: bootstrap
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          AWS_REGION: us-east-1
          DYNAMODB_TABLE: chargebacks-lambda
          LOG_LEVEL: INFO
          LOG_FORMAT: json
          SERVICE_NAME: chargeback-lambda

Outputs:
  ChargebackApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"